# Generated by Django 5.2.3 on 2025-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pornvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='pornvideo',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
