# Generated by Django 5.2.3 on 2025-06-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porno', '0002_remove_pornvideo_video_file_pornvideo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pornvideo',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
